/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as Auth2faRouteImport } from './routes/auth.2fa'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedRecordingsIndexRouteImport } from './routes/_authenticated/recordings.index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring.index'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedCallsIndexRouteImport } from './routes/_authenticated/calls.index'
import { Route as AuthenticatedTelephonySettingsRouteImport } from './routes/_authenticated/telephony.settings'
import { Route as AuthenticatedSecurityAuditRouteImport } from './routes/_authenticated/security.audit'
import { Route as AuthenticatedQaDashboardRouteImport } from './routes/_authenticated/qa.dashboard'
import { Route as AuthenticatedQaCriteriaRouteImport } from './routes/_authenticated/qa.criteria'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts.$id'
import { Route as AuthenticatedClientsImportRouteImport } from './routes/_authenticated/clients.import'
import { Route as AuthenticatedClientsApprovalsRouteImport } from './routes/_authenticated/clients.approvals'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedCallsNewRouteImport } from './routes/_authenticated/calls.new'
import { Route as AuthenticatedCallsIdRouteImport } from './routes/_authenticated/calls.$id'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const Auth2faRoute = Auth2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordingsIndexRoute =
  AuthenticatedRecordingsIndexRouteImport.update({
    id: '/recordings/',
    path: '/recordings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCallsIndexRoute = AuthenticatedCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTelephonySettingsRoute =
  AuthenticatedTelephonySettingsRouteImport.update({
    id: '/telephony/settings',
    path: '/telephony/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecurityAuditRoute =
  AuthenticatedSecurityAuditRouteImport.update({
    id: '/security/audit',
    path: '/security/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQaDashboardRoute =
  AuthenticatedQaDashboardRouteImport.update({
    id: '/qa/dashboard',
    path: '/qa/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQaCriteriaRoute = AuthenticatedQaCriteriaRouteImport.update({
  id: '/qa/criteria',
  path: '/qa/criteria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsImportRoute =
  AuthenticatedClientsImportRouteImport.update({
    id: '/clients/import',
    path: '/clients/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsApprovalsRoute =
  AuthenticatedClientsApprovalsRouteImport.update({
    id: '/clients/approvals',
    path: '/clients/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsNewRoute = AuthenticatedCallsNewRouteImport.update({
  id: '/calls/new',
  path: '/calls/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsIdRoute = AuthenticatedCallsIdRouteImport.update({
  id: '/calls/$id',
  path: '/calls/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/2fa': typeof Auth2faRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/calls/$id': typeof AuthenticatedCallsIdRoute
  '/calls/new': typeof AuthenticatedCallsNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/approvals': typeof AuthenticatedClientsApprovalsRoute
  '/clients/import': typeof AuthenticatedClientsImportRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/qa/criteria': typeof AuthenticatedQaCriteriaRoute
  '/qa/dashboard': typeof AuthenticatedQaDashboardRoute
  '/security/audit': typeof AuthenticatedSecurityAuditRoute
  '/telephony/settings': typeof AuthenticatedTelephonySettingsRoute
  '/calls/': typeof AuthenticatedCallsIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/recordings/': typeof AuthenticatedRecordingsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/2fa': typeof Auth2faRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/calls/$id': typeof AuthenticatedCallsIdRoute
  '/calls/new': typeof AuthenticatedCallsNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/approvals': typeof AuthenticatedClientsApprovalsRoute
  '/clients/import': typeof AuthenticatedClientsImportRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/qa/criteria': typeof AuthenticatedQaCriteriaRoute
  '/qa/dashboard': typeof AuthenticatedQaDashboardRoute
  '/security/audit': typeof AuthenticatedSecurityAuditRoute
  '/telephony/settings': typeof AuthenticatedTelephonySettingsRoute
  '/calls': typeof AuthenticatedCallsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/recordings': typeof AuthenticatedRecordingsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/2fa': typeof Auth2faRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/calls/$id': typeof AuthenticatedCallsIdRoute
  '/_authenticated/calls/new': typeof AuthenticatedCallsNewRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/approvals': typeof AuthenticatedClientsApprovalsRoute
  '/_authenticated/clients/import': typeof AuthenticatedClientsImportRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/qa/criteria': typeof AuthenticatedQaCriteriaRoute
  '/_authenticated/qa/dashboard': typeof AuthenticatedQaDashboardRoute
  '/_authenticated/security/audit': typeof AuthenticatedSecurityAuditRoute
  '/_authenticated/telephony/settings': typeof AuthenticatedTelephonySettingsRoute
  '/_authenticated/calls/': typeof AuthenticatedCallsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/recordings/': typeof AuthenticatedRecordingsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/auth/2fa'
    | '/auth/forgot'
    | '/admin/permissions'
    | '/calls/$id'
    | '/calls/new'
    | '/clients/$id'
    | '/clients/approvals'
    | '/clients/import'
    | '/contacts/$id'
    | '/qa/criteria'
    | '/qa/dashboard'
    | '/security/audit'
    | '/telephony/settings'
    | '/calls/'
    | '/clients/'
    | '/contacts/'
    | '/monitoring/'
    | '/recordings/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/auth/2fa'
    | '/auth/forgot'
    | '/admin/permissions'
    | '/calls/$id'
    | '/calls/new'
    | '/clients/$id'
    | '/clients/approvals'
    | '/clients/import'
    | '/contacts/$id'
    | '/qa/criteria'
    | '/qa/dashboard'
    | '/security/audit'
    | '/telephony/settings'
    | '/calls'
    | '/clients'
    | '/contacts'
    | '/monitoring'
    | '/recordings'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/auth/2fa'
    | '/auth/forgot'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/calls/$id'
    | '/_authenticated/calls/new'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/approvals'
    | '/_authenticated/clients/import'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/qa/criteria'
    | '/_authenticated/qa/dashboard'
    | '/_authenticated/security/audit'
    | '/_authenticated/telephony/settings'
    | '/_authenticated/calls/'
    | '/_authenticated/clients/'
    | '/_authenticated/contacts/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/recordings/'
    | '/_authenticated/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/2fa': {
      id: '/auth/2fa'
      path: '/2fa'
      fullPath: '/auth/2fa'
      preLoaderRoute: typeof Auth2faRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recordings/': {
      id: '/_authenticated/recordings/'
      path: '/recordings'
      fullPath: '/recordings/'
      preLoaderRoute: typeof AuthenticatedRecordingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls/': {
      id: '/_authenticated/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof AuthenticatedCallsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/telephony/settings': {
      id: '/_authenticated/telephony/settings'
      path: '/telephony/settings'
      fullPath: '/telephony/settings'
      preLoaderRoute: typeof AuthenticatedTelephonySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/audit': {
      id: '/_authenticated/security/audit'
      path: '/security/audit'
      fullPath: '/security/audit'
      preLoaderRoute: typeof AuthenticatedSecurityAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa/dashboard': {
      id: '/_authenticated/qa/dashboard'
      path: '/qa/dashboard'
      fullPath: '/qa/dashboard'
      preLoaderRoute: typeof AuthenticatedQaDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa/criteria': {
      id: '/_authenticated/qa/criteria'
      path: '/qa/criteria'
      fullPath: '/qa/criteria'
      preLoaderRoute: typeof AuthenticatedQaCriteriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/import': {
      id: '/_authenticated/clients/import'
      path: '/clients/import'
      fullPath: '/clients/import'
      preLoaderRoute: typeof AuthenticatedClientsImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/approvals': {
      id: '/_authenticated/clients/approvals'
      path: '/clients/approvals'
      fullPath: '/clients/approvals'
      preLoaderRoute: typeof AuthenticatedClientsApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls/new': {
      id: '/_authenticated/calls/new'
      path: '/calls/new'
      fullPath: '/calls/new'
      preLoaderRoute: typeof AuthenticatedCallsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls/$id': {
      id: '/_authenticated/calls/$id'
      path: '/calls/$id'
      fullPath: '/calls/$id'
      preLoaderRoute: typeof AuthenticatedCallsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedCallsIdRoute: typeof AuthenticatedCallsIdRoute
  AuthenticatedCallsNewRoute: typeof AuthenticatedCallsNewRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsApprovalsRoute: typeof AuthenticatedClientsApprovalsRoute
  AuthenticatedClientsImportRoute: typeof AuthenticatedClientsImportRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedQaCriteriaRoute: typeof AuthenticatedQaCriteriaRoute
  AuthenticatedQaDashboardRoute: typeof AuthenticatedQaDashboardRoute
  AuthenticatedSecurityAuditRoute: typeof AuthenticatedSecurityAuditRoute
  AuthenticatedTelephonySettingsRoute: typeof AuthenticatedTelephonySettingsRoute
  AuthenticatedCallsIndexRoute: typeof AuthenticatedCallsIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
  AuthenticatedRecordingsIndexRoute: typeof AuthenticatedRecordingsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedCallsIdRoute: AuthenticatedCallsIdRoute,
  AuthenticatedCallsNewRoute: AuthenticatedCallsNewRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsApprovalsRoute: AuthenticatedClientsApprovalsRoute,
  AuthenticatedClientsImportRoute: AuthenticatedClientsImportRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedQaCriteriaRoute: AuthenticatedQaCriteriaRoute,
  AuthenticatedQaDashboardRoute: AuthenticatedQaDashboardRoute,
  AuthenticatedSecurityAuditRoute: AuthenticatedSecurityAuditRoute,
  AuthenticatedTelephonySettingsRoute: AuthenticatedTelephonySettingsRoute,
  AuthenticatedCallsIndexRoute: AuthenticatedCallsIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  AuthenticatedRecordingsIndexRoute: AuthenticatedRecordingsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  Auth2faRoute: typeof Auth2faRoute
  AuthForgotRoute: typeof AuthForgotRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth2faRoute: Auth2faRoute,
  AuthForgotRoute: AuthForgotRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
