/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts.index'
import { Route as AuthenticatedCallsIndexRouteImport } from './routes/_authenticated/calls.index'
import { Route as AuthenticatedSecurityAuditRouteImport } from './routes/_authenticated/security.audit'
import { Route as AuthenticatedQaDashboardRouteImport } from './routes/_authenticated/qa.dashboard'
import { Route as AuthenticatedQaCriteriaRouteImport } from './routes/_authenticated/qa.criteria'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts.$id'
import { Route as AuthenticatedCallsNewRouteImport } from './routes/_authenticated/calls.new'
import { Route as AuthenticatedCallsIdRouteImport } from './routes/_authenticated/calls.$id'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCallsIndexRoute = AuthenticatedCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityAuditRoute =
  AuthenticatedSecurityAuditRouteImport.update({
    id: '/security/audit',
    path: '/security/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQaDashboardRoute =
  AuthenticatedQaDashboardRouteImport.update({
    id: '/qa/dashboard',
    path: '/qa/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQaCriteriaRoute = AuthenticatedQaCriteriaRouteImport.update({
  id: '/qa/criteria',
  path: '/qa/criteria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsNewRoute = AuthenticatedCallsNewRouteImport.update({
  id: '/calls/new',
  path: '/calls/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsIdRoute = AuthenticatedCallsIdRouteImport.update({
  id: '/calls/$id',
  path: '/calls/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/calls/$id': typeof AuthenticatedCallsIdRoute
  '/calls/new': typeof AuthenticatedCallsNewRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/qa/criteria': typeof AuthenticatedQaCriteriaRoute
  '/qa/dashboard': typeof AuthenticatedQaDashboardRoute
  '/security/audit': typeof AuthenticatedSecurityAuditRoute
  '/calls/': typeof AuthenticatedCallsIndexRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/calls/$id': typeof AuthenticatedCallsIdRoute
  '/calls/new': typeof AuthenticatedCallsNewRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/qa/criteria': typeof AuthenticatedQaCriteriaRoute
  '/qa/dashboard': typeof AuthenticatedQaDashboardRoute
  '/security/audit': typeof AuthenticatedSecurityAuditRoute
  '/calls': typeof AuthenticatedCallsIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/calls/$id': typeof AuthenticatedCallsIdRoute
  '/_authenticated/calls/new': typeof AuthenticatedCallsNewRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/qa/criteria': typeof AuthenticatedQaCriteriaRoute
  '/_authenticated/qa/dashboard': typeof AuthenticatedQaDashboardRoute
  '/_authenticated/security/audit': typeof AuthenticatedSecurityAuditRoute
  '/_authenticated/calls/': typeof AuthenticatedCallsIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/permissions'
    | '/calls/$id'
    | '/calls/new'
    | '/contacts/$id'
    | '/qa/criteria'
    | '/qa/dashboard'
    | '/security/audit'
    | '/calls/'
    | '/contacts/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/permissions'
    | '/calls/$id'
    | '/calls/new'
    | '/contacts/$id'
    | '/qa/criteria'
    | '/qa/dashboard'
    | '/security/audit'
    | '/calls'
    | '/contacts'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/calls/$id'
    | '/_authenticated/calls/new'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/qa/criteria'
    | '/_authenticated/qa/dashboard'
    | '/_authenticated/security/audit'
    | '/_authenticated/calls/'
    | '/_authenticated/contacts/'
    | '/_authenticated/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls/': {
      id: '/_authenticated/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof AuthenticatedCallsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/audit': {
      id: '/_authenticated/security/audit'
      path: '/security/audit'
      fullPath: '/security/audit'
      preLoaderRoute: typeof AuthenticatedSecurityAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa/dashboard': {
      id: '/_authenticated/qa/dashboard'
      path: '/qa/dashboard'
      fullPath: '/qa/dashboard'
      preLoaderRoute: typeof AuthenticatedQaDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa/criteria': {
      id: '/_authenticated/qa/criteria'
      path: '/qa/criteria'
      fullPath: '/qa/criteria'
      preLoaderRoute: typeof AuthenticatedQaCriteriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls/new': {
      id: '/_authenticated/calls/new'
      path: '/calls/new'
      fullPath: '/calls/new'
      preLoaderRoute: typeof AuthenticatedCallsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls/$id': {
      id: '/_authenticated/calls/$id'
      path: '/calls/$id'
      fullPath: '/calls/$id'
      preLoaderRoute: typeof AuthenticatedCallsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedCallsIdRoute: typeof AuthenticatedCallsIdRoute
  AuthenticatedCallsNewRoute: typeof AuthenticatedCallsNewRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedQaCriteriaRoute: typeof AuthenticatedQaCriteriaRoute
  AuthenticatedQaDashboardRoute: typeof AuthenticatedQaDashboardRoute
  AuthenticatedSecurityAuditRoute: typeof AuthenticatedSecurityAuditRoute
  AuthenticatedCallsIndexRoute: typeof AuthenticatedCallsIndexRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedCallsIdRoute: AuthenticatedCallsIdRoute,
  AuthenticatedCallsNewRoute: AuthenticatedCallsNewRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedQaCriteriaRoute: AuthenticatedQaCriteriaRoute,
  AuthenticatedQaDashboardRoute: AuthenticatedQaDashboardRoute,
  AuthenticatedSecurityAuditRoute: AuthenticatedSecurityAuditRoute,
  AuthenticatedCallsIndexRoute: AuthenticatedCallsIndexRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
